config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges, only: [:new, :create]

  post 'downgrade', to: 'users#downgrade'
  get 'downgrade_confirmation', to: 'users#downgrade_confirmation'

  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 5 }, presence: true
  validates :private, inclusion: { in: [true, false ] }

  default_scope { order('created_at DESC') }

  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    # @wiki_cols = User.where(id: @wiki.collaborators.pluck(:user_id))
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved"
      redirect_to @wiki
    else
      flash[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @wiki.user = current_user
    @users = User.all
    @collaborators = @wiki.collaborators
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved"
      redirect_to @wiki
    else
      flash[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error deleting the wiki."
      redirect_to @wiki
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_wiki?(wiki)
    current_user && (current_user == wiki.user || current_user.admin?)
  end

  def wiki_has_collaborators?
    @wiki.collaborators.any?
  end 
end

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <% if @wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@wiki.errors.count, "error") %>.</h4>
      <ul>
        <% @wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(@wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(@wiki.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_field :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>
  <% if current_user.admin? || (current_user.premium? && current_user == @wiki.user) %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private Wiki
      <% end %>
    </div>
  <% end %>
  <%= f.submit "Save", class: 'btn btn-success' %>
  <%= link_to 'Cancel', wikis_path, class: 'btn btn-danger' %>
<% end %>

app/views/wikis/_wiki.html.erb
<div class="row">
  <div class="col-md-8">
    <h4><%= link_to wiki.title, wiki %></h4>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-info' %>
    <%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>
<hr>

app/views/wikis/edit.html.erb
<div class="page-header">
  <h1>Edit "<%= @wiki.title %>"</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>The first rule of Blocipedia is don't talk about Blocipedia.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
    <%= render partial: 'collaborators/collaborator', locals: { wiki: @wiki, user: @user } %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>All Wikis</h1>
  </div>
  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

<br>

<div class='row'>
  <div class='col-md-8'>
    <% @wikis.each do |wiki| %>
      <h4><%= link_to wiki.title, wiki %></h4>
      <h6>Published <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.username %></h6>
      <% if wiki != @wikis.last %>
      &nbsp;
      <br>
        -----
      <% end %>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>The first rule of Blocipedia is don't talk about Blocipedia.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container">
  <% if policy(@wiki).show? %>
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <%= @wiki.title %> <br>
          <% if @wiki.private == true %>
            <span class="label label-warning">Private</span>
          <% end %>
          <small>
            created <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.username %>
          </small>
        </div>
        <hr>
        <div class="row">
          <p><%= markdown(@wiki.body) %></p>
        </div>
      </div>
      <div class="col-md-4">
        <% if policy(@wiki).update? %>
          <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-info' %>
        <% end %>
        <% if policy(@wiki).destroy? %>
          <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
    &nbsp;
    <% if @wiki.private == true %>
      <h4>Collaborators</h4>
      <% if @wiki.collaborators.count == 0 %>
        <small> There are no collaborators on this wiki </small>
      <% else %>
        <% @wiki.collaborators.each do |collaborator| %>
          <li><%= collaborator.user.username %></li>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>