config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

  resources :charges, only: [:new, :create]

  post 'downgrade', to: 'users#downgrade'
  get 'downgrade_confirmation', to: 'users#downgrade_confirmation'

  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=devce-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>

        <div class="pull-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.username %></strong> <br>
            <% if current_user.standard? %>
              <%= link_to 'Upgrade to Premium', new_charge_path, :class => 'navbar-link' %> -
            <% elsif current_user.premium? %>
              <%= link_to 'Downgrade to Standard', downgrade_path, method: :post, :class => 'navbar-link' %> -
            <% end %>
            <%= link_to 'Edit profie', edit_user_registration_path, :class => 'navbar-link' %> -
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
          <% end %>
        </div>
      </ul>



      <%= yield %>
    </div>
  </body>
</html>